### PR TITLE
.NET 6.0 auto testing

### PR DESCRIPTION
**Pull request by NealGeilen**
feat: When a pull request is issued to the main branch a code test will be issued.

### CODE REVIEW

**Review by kanersps — CHANGES_REQUESTED** [review]
Looks good, but please name the workflow for what it's supposed to do.

Eg for this one, instead of ".NET" something like "Test API" or equivelant

**Comment by NealGeilen** [comment]
I have renamed it to "build test".  
When we have made enough API endpoints there will be a separate action made that will test those endpoints.
That action will be named  "API Test" or "API endpoint test" something like that

**Comment by kanersps** [comment]
I think you forgot to add the new file to the commit, the repo doesn't contain the new yml file.

**Review by kanersps — APPROVED** [review]
Great!

**Pull request merged**
