### PR TITLE
LPR-20 Docker update

### PR DESCRIPTION
**Pull request by NealGeilen**
Testing new CI pipeline

Please don't review until requested

### CODE REVIEW

**Comment by NealGeilen** [comment]
For review. 
Please rebuild the images and check if you can access the API on: https://localhost:5001/index.html

**Review by WouterPennings — COMMENTED** [review]
I think It looks good, but I do not have much knowledge on this

**Review by DamienKusters — CHANGES_REQUESTED** [review]
The API keeps crashing on my device.
Exception that pops up:
**Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file**

**Review by nickonos — APPROVED** [review]
It Works!

**Review by DamienKusters — APPROVED** [review]
Tested, & it works!

**Pull request merged**
